defaults:
  # both work for referencing the task config
  - ../robotwin_task_config/blocks_stack_easy@robotwin_task_config
  # - ../robotwin_task_config@robotwin_task_config: apple_cabinet_storage

name: blocks_stack_easy_2

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 6]
      type: point_cloud
    agent_pos:
      shape: [14]
      type: low_dim
  action:
    shape: [14]

env_runner:
  _target_: maniflow.env_runner.robot_runner.RobotRunner
  eval_episodes: 10 # 20
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  task_name: blocks_stack_easy
  task_config: ${robotwin_task.robotwin_task_config}

dataset:
  _target_: maniflow.dataset.robot_feature_dataset.RobotFeatDataset
  zarr_path: data/blocks_stack_easy_2.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
  max_train_episodes: null
