defaults:
  # both work for referencing the task config
  - ../robotwin_task_config/diverse_bottles_pick@robotwin_task_config
  # - ../robotwin_task_config@robotwin_task_config: diverse_bottles_pick

name: diverse_bottles_pick

image_shape: &image_shape [3, 224, 224] # [3, 240, 320]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    head_cam:
      shape: *image_shape
      type: rgb
      horizon: ${n_obs_steps}
    point_cloud:
      shape: [1024, 6]
      type: point_cloud
      horizon: ${n_obs_steps}
    agent_pos:
      shape: [14]
      type: low_dim
      horizon: ${n_obs_steps}
  action:
    shape: [14]
    horizon: ${horizon}

env_runner:
  _target_: maniflow.env_runner.robot_runner.RobotRunner
  eval_episodes: 10 # 20
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  task_name: diverse_bottles_pick
  task_config: ${robotwin_task.robotwin_task_config}

dataset:
  _target_: maniflow.dataset.robotwin_dataset.RoboTwinDataset
  # zarr_path: data/diverse_bottles_pick_50.zarr
  zarr_path: data/robotwin_gen_data/diverse_bottles_pick_50.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
  max_train_episodes: null
  use_img: true
  use_point_cloud: false
  normalize_agent_pos: false
