defaults:
  # both work for referencing the task config
  - ../robotwin_task_config/empty_cup_place@robotwin_task_config
  # - ../robotwin_task_config@robotwin_task_config: diverse_bottles_pick

name: empty_cup_place

obs_horizon: &obs_horizon 2
action_horizon: &action_horizon 8
image_shape: &image_shape [3, 240, 320] # [3, 240, 320]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    head_cam:
      shape: *image_shape
      type: rgb
      horizon: *obs_horizon
    point_cloud:
      shape: [1024, 6]
      type: point_cloud
      horizon: *obs_horizon
    agent_pos:
      shape: [14]
      type: low_dim
      horizon: *obs_horizon
  action:
    shape: [14]
    horizon: *action_horizon

env_runner:
  _target_: maniflow.env_runner.robot_runner.RobotRunner
  eval_episodes: 10 # 20
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  task_name: empty_cup_place
  task_config: ${robotwin_task.robotwin_task_config}

dataset:
  _target_: maniflow.dataset.robotwin_dataset.RoboTwinDataset
  # zarr_path: data/empty_cup_place_50.zarr
  zarr_path: data/robotwin_gen_data/empty_cup_place_50.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
  max_train_episodes: null
  use_img: true
  use_point_cloud: false
  normalize_agent_pos: false
