defaults:
  # both work for referencing the task config
  - ../robotwin_task_config/robotwin_multitask@robotwin_task_config
  # - ../robotwin_task_config@robotwin_task_config: robotwin_multitask

name: robotwin_multitask

task_names: 
  - apple_cabinet_storage_50
  - shoe_place_50
  - pick_apple_messy_50

raw_task_names: 
  - apple_cabinet_storage
  - shoe_place
  - pick_apple_messy

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 6]
      type: point_cloud
    agent_pos:
      shape: [14]
      type: low_dim
  action:
    shape: [14]

env_runner:
  _target_: maniflow.env_runner.robot_multitask_runner.RobotMultitaskRunner
  # _target_: maniflow.env_runner.robot_multitask_runner_mp.RobotMultitaskRunner
  eval_episodes: 10 # 20
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  task_names: ${robotwin_task.task_names}
  devices: null
  multitask_config: ${robotwin_task.robotwin_task_config}
  max_processes: 1

dataset:
  _target_: maniflow.dataset.robotwin_multitask_dataset.RobotwinMultitaskDataset
  # _target_: maniflow.dataset.robotwin_multitask_dataset.RobotwinMultitaskDataset
  data_path: data/
  task_names: ${robotwin_task.task_names}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
  max_train_episodes: 10000
