name: ${task_name}-${setting}-${expert_data_num}

image_shape: &image_shape [3, 224, 224] # [3, 240, 320], [3, 224, 224]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    head_cam:
      shape: *image_shape
      type: rgb
      horizon: ${n_obs_steps}
    # point_cloud:
    #   shape: [1024, 6]
    #   type: point_cloud
    #   horizon: ${n_obs_steps}
    left_wrist_cam:
      shape: *image_shape
      type: rgb
      horizon: ${n_obs_steps}
    right_wrist_cam:
      shape: *image_shape
      type: rgb
      horizon: ${n_obs_steps}
    
    agent_pos:
      shape: [14]
      type: low_dim
      horizon: ${n_obs_steps}
  action:
    shape: [14]
    horizon: ${horizon}

env_runner:
  _target_: maniflow.env_runner.robotwin_runner.RobotRunner
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  task_name: robot

dataset:
  _target_: maniflow.dataset.robotwin_image_dataset.RoboTwinImageDataset
  zarr_path: data/${task.name}.zarr
  horizon: ${horizon}
  n_obs_steps: ${n_obs_steps}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
  max_train_episodes: null
  shape_meta: ${shape_meta}
  #map image key to buffer key
  obs_key_mapping:
    head_cam: head_camera
    left_wrist_cam: left_camera
    right_wrist_cam: right_camera
    agent_pos: state
  state_key: state
  action_key: action